language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run build-lib
before_deploy:
  - cd dist/firebaseui-angular-library
deploy:
  provider: npm
  email: info@rjenni.ch
  api_token:
    secure: DTHTJ0WLEgJQ7MwoI27BI+S9mQmScLsWMb+iOr0Hkir5GDJxF6lLHU2WVrH3n/a9BgcbH3E+6Gpm55O1M6R/Cda2pXoCWgpC5nD9q2A40B1OBvFcWWv42TRYHy8nDpNK1KllJjWzF7Z10k8rgINWLqogtQnvtt4RGTL6XdD8D3fTNw1KCsY3QRI2RLgzxJ7bysd6CW2grc00lgEjI7T0CJj/4sPOmNUpXoOd0Ecqi8ImDa9iZJOatc9OnBrriYCoq3OaZYjC2Yo14uKKZ+G8132CsXlPoiMZrNYDnC7bh43do/NL4fhJf9uAHT9iUELfxMhlirZ0HQGspyriXXDvGej4Hi9l5axwA2WxeJusw0Oh3iMELAkCXIlhJ7CfYFJ1drA28I6hUzmBm9+nADzfTpyNMd12d/8y6GSz+WDJGVSdbLzL+JsaHogOhUiuNObaUrBs1AnJQtC+guQ5ACDK68VOnX59obEsBakrGwQQTR8XuqEWytvC/l9gR46x6mWk+eRkPJF5V124Q8ZSFfE1u2M/fPaFffGgqKZ8upuAdAVNUey+ygfU440/8fXlgBNEFl9ZhYI9CqNULRij2hEX4GXvmQgvMIRvLOXaoS2cjhfnpd0y4pb6TJyBb8TFJnuL9AUVSBPaEzJpN3wkmUINPlWMQ4kiJAuxJcXXviCnZ2g=
  on:
    branch: master
    tags: true
    repo: RaphaelJenni/FirebaseUI-Angular
notifications:
  email:
    recipients:
      - "$EMAIL"
    on_failure: always
    on_success: always
